services:
    db_diary:
        image: mysql:8.0
        ports:
            - "5555:3306"
        container_name: diary-mysql
        restart: unless-stopped
        volumes:
            - ./data_mysql:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: adm
            MYSQL_DATABASE: diary
            MYSQL_USER: adm
            MYSQL_PASSWORD: adm
