services:
  api:
    container_name: api_diary_run
    build:
      context: ./back/diary
      dockerfile: Dockerfile.spring
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/diary
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: admin
    restart: unless-stopped

  db:
    container_name: db_diary
    image: mysql:8.0
    expose:
      - "3306"
    restart: unless-stopped
    volumes:
      - ./data_mysql:/var/lib/mysql
    environment:
      MYSQL_DATABASE: diary
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
      MYSQL_ROOT_PASSWORD: admin

  ui:
    container_name: front_diary_ui
    build:
      context: ./front-end
      dockerfile: Dockerfile.ui
    ports:
      - "5173:5173"
    depends_on:
      - api
      - db
    restart: unless-stopped
