services:
  diary_databse:
    image: mysql:8.0
    ports:
      - "5005:3306"
    container_name: diary_mysql
    restart: unless-stopped
    volumes:
      - ./data_mysql:/var/lib/mysql
    environment:
      MYSQL_DATABASE: diary
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
      MYSQL_ROOT_PASSWORD: admin
